### ISSUE TITLE
List index out of range in wallInteraction

### ISSUE THREAD

**Issue by ZedThree** [boutproject/hypnotoad2#9]
```
hypnotoad2: hypnotoad2_geqdsk mast.geqdsk 
  nx = 65, ny = 65
102

Options
=======
Name                                              |  Value                         
--------------------------------------------------------------------------------
cap_Bp_ylow_xpoint                                |  False      (default)               
curvature_type                                    |  curl(b/B) with x-y derivatives     (default)
finecontour_Nfine                                 |  100        (default)                 
finecontour_atol                                  |  1e-12      (default)               
finecontour_diagnose                              |  False      (default)               
finecontour_maxits                                |  200        (default)                 
follow_perpendicular_atol                         |  1e-08      (default)               
follow_perpendicular_rtol                         |  2e-08      (default)               
geometry_rtol                                     |  1e-10      (default)               
nonorthogonal_radial_range_power                  |  1.0        (default)                 
nonorthogonal_spacing_method                      |  combined   (default)            
nonorthogonal_target_poloidal_spacing_length      |  None       (default)                
nonorthogonal_target_poloidal_spacing_range       |  None       (default)                
nonorthogonal_target_poloidal_spacing_range_inner |  None       (default)                
nonorthogonal_target_poloidal_spacing_range_outer |  None       (default)                
nonorthogonal_xpoint_poloidal_spacing_length      |  0.05       (default)                
nonorthogonal_xpoint_poloidal_spacing_range       |  None       (default)                
nonorthogonal_xpoint_poloidal_spacing_range_inner |  None       (default)                
nonorthogonal_xpoint_poloidal_spacing_range_outer |  None       (default)                
nx_core                                           |  5  (default)                   
nx_pf                                             |  5                             
nx_pf_lower                                       |  None       (default)                
nx_pf_upper                                       |  None       (default)                
nx_sol                                            |  5  (default)                   
nx_sol_inner                                      |  5                             
nx_sol_outer                                      |  5                             
ny_inner_divertor                                 |  4  (default)                   
ny_inner_lower_divertor                           |  4                             
ny_inner_sol                                      |  4                             
ny_inner_upper_divertor                           |  4                             
ny_outer_divertor                                 |  4  (default)                   
ny_outer_lower_divertor                           |  4                             
ny_outer_sol                                      |  4                             
ny_outer_upper_divertor                           |  4                             
ny_sol                                            |  8  (default)                   
orthogonal                                        |  True       (default)                
poloidal_spacing_delta_psi                        |  0.00125012279304738           
poloidal_spacing_method                           |  sqrt       (default)                
poloidalfunction_diagnose                         |  False      (default)               
psi_core                                          |  -0.11251105137437345          
psi_pf_lower                                      |  -0.11251105137437345          
psi_pf_upper                                      |  -0.11251105137437345          
psi_sol                                           |  -0.13751350723532105          
psi_sol_inner                                     |  -0.13751350723532105          
psi_spacing_separatrix_multiplier                 |  None       (default)                
psinorm_core                                      |  0.9        (default)                 
psinorm_pf                                        |  0.9                           
psinorm_pf_lower                                  |  0.9                           
psinorm_pf_upper                                  |  0.9                           
psinorm_sol                                       |  1.1        (default)                 
psinorm_sol_inner                                 |  1.1                           
refine_atol                                       |  2e-08      (default)               
refine_methods                                    |  integrate+newton, integrate        (default)
refine_width                                      |  0.01       (default)                
sfunc_checktol                                    |  1e-13      (default)               
shiftedmetric                                     |  True       (default)                
target_poloidal_spacing_length                    |  None       (default)                
xpoint_poloidal_spacing_length                    |  0.05       (default)                
y_boundary_guards                                 |  0  (default)                   

Traceback (most recent call last):
  File "/home/peter/Codes/hypnotoad2/hypnotoad_test_venv/bin/hypnotoad2_geqdsk", line 11, in <module>
    load_entry_point('hypnotoad2', 'console_scripts', 'hypnotoad2_geqdsk')()
  File "/home/peter/Codes/hypnotoad2/hypnotoad2/scripts/hypnotoad2_geqdsk.py", line 32, in main
    eq = tokamak.read_geqdsk(fh, options=options)
  File "/home/peter/Codes/hypnotoad2/hypnotoad2/cases/tokamak.py", line 1521, in read_geqdsk
    **kwargs
  File "/home/peter/Codes/hypnotoad2/hypnotoad2/cases/tokamak.py", line 236, in __init__
    self.makeRegions()
  File "/home/peter/Codes/hypnotoad2/hypnotoad2/cases/tokamak.py", line 489, in makeRegions
    leg_regions, core_regions, segments, connections = self.describeDoubleNull()
  File "/home/peter/Codes/hypnotoad2/hypnotoad2/cases/tokamak.py", line 722, in describeDoubleNull
    lower_legs = self.findLegs(lower_x_point)
  File "/home/peter/Codes/hypnotoad2/hypnotoad2/cases/tokamak.py", line 323, in findLegs
    intersect = self.wallIntersection(Point2D(*pos), Point2D(*newpos))
  File "/home/peter/Codes/hypnotoad2/hypnotoad2/core/equilibrium.py", line 2967, in wallIntersection
    closed_wall = self.wall + [self.wall[0]]
IndexError: list index out of range
```

This is with a GEQDSK file generated by freegs from the `03-mast.py` example (attached, ignore the `.log` extension that's just so github will let me upload it!)
[mast.geqdsk.log](https://github.com/boutproject/hypnotoad2/files/4487784/mast.geqdsk.log)

**Comment by johnomotani** [comment]
Ah, I think I see what's happening. Your geqdsk file has no wall, and `TokamakEquilibrium.__init__()` handles `wall is None`, but `read_geqdsk` actually passes `wall = []` when there is no wall info. I'll make a PR to fix.
